function M0203_sort = importfile(filename, dataLines)
%IMPORTFILE Import data from text file
% M0203 = IMPORTFILE(FILENAME) reads the data of the default selected range in the text file FILENAME.  Return data in table form.
%
% M0203 = IMPORTFILE(FILE, DATALINES) reads text file FILENAME at specified line intervals
data in %. For discontinuous row spacing, specify DATALINES as a positive integer scalar or an N-by-2 array of positive integer scalars.
%
% Example:
% M0203 = importfile("C:\Users\Swarnali\visionbf\vision-bf\data\UAV-benchmark-MOTD_v1.0\RES_MOT\YOLOv5\SORT\M0203.txt", [1, Inf]);
%
% See also READTABLE.
%
% Automatically generated by MATLAB on 2023-06-17 14:48:36
%% input processing

% If dataLines is not specified, define a default range
if nargin < 2
    dataLines = [1, Inf];
end

%% Set import options and import data
opts = delimitedTextImportOptions("NumVariables", 5);

% specifies the range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column name and type
opts.VariableNames = ["frame_idx", "car_id", "phi", "theta", "distance"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file-level attributes
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import data
M0203_sort = readtable(filename, opts);

end