path: ../dataset  # dataset root dir
train: train.txt  # train images (relative to 'path') 
val: val.txt  # val images (relative to 'path') 
test: test.txt  

nc: 1  # number of classes
names:
  0: car